# Source Registry — Recommended Package
# Schema: rules/schemas/sources.schema.yml
# Contains only sources backing rules in the RRAILS/RRAILS_CLAUDE namespaces.
- id: agents-md-spec
  url: https://agents.md/
  type: official
  weight: 1.0
  title: Agents.md Specification
- id: awesome-copilot-meta-instructions
  url: 
    https://raw.githubusercontent.com/github/awesome-copilot/main/instructions/instructions.instructions.md
  type: community
  weight: 0.6
  title: Awesome Copilot Meta-Instructions
- id: claude-code-issue-13579
  url: https://github.com/anthropics/claude-code/issues/13579
  type: community
  weight: 0.6
  title: 'Claude Code Issue #13579 - Token Waste'
- id: claude-code-memory
  url: https://code.claude.com/docs/en/memory
  type: official
  weight: 1.0
  title: Claude Code Memory Documentation
- id: claude-md-guide
  url: https://www.builder.io/blog/claude-md-guide
  type: community
  weight: 0.6
  title: Claude.md Guide - Builder.io
- id: copilot-cli-best-practices
  url: https://docs.github.com/en/copilot/how-tos/copilot-cli/cli-best-practices
  type: official
  weight: 1.0
  title: Copilot CLI Best Practices
- id: dometrain-claude-md-guide
  url: https://dometrain.com/blog/creating-the-perfect-claudemd-for-claude-code/
  type: community
  weight: 0.6
  title: Creating the Perfect CLAUDE.md - Dometrain
- id: enterprise-claude-usage
  url: https://blog.sshh.io/p/how-i-use-every-claude-code-feature
  type: community
  weight: 0.6
  title: How I Use Every Claude Code Feature
- id: instruction-limits-principles
  url: https://www.humanlayer.dev/blog/writing-a-good-claude-md
  type: community
  weight: 0.6
  title: Writing a Good Claude.md - HumanLayer
- id: monorepo-claude-md-organization
  url: 
    https://dev.to/anvodev/how-i-organized-my-claudemd-in-a-monorepo-with-too-many-contexts-37k7
  type: community
  weight: 0.6
  title: Monorepo Claude.md Organization
- id: rules-directory-mechanics
  url: https://claudefa.st/blog/guide/mechanics/rules-directory
  type: community
  weight: 0.6
  title: Rules Directory Mechanics - ClaudeFast
- id: spec-writing-for-agents
  url: https://addyosmani.com/blog/good-spec/
  type: research
  weight: 0.8
  title: Writing Good Specs for AI Agents - Addy Osmani
