# Source Registry — Recommended Package
# Schema: rules/schemas/sources.schema.yml
# Contains only sources backing rules in the RRAILS/RRAILS_CLAUDE namespaces.
- id: advanced-context-engineering
  url: 
    https://github.com/humanlayer/advanced-context-engineering-for-coding-agents
  type: research
  weight: 0.8
  title: Advanced Context Engineering for Coding Agents
- id: agents-md-spec
  url: https://agents.md/
  type: official
  weight: 1.0
  title: Agents.md Specification
- id: anthropic-teams-claude-code
  url: https://claude.com/blog/how-anthropic-teams-use-claude-code
  type: official
  weight: 1.0
  title: How Anthropic Teams Use Claude Code
- id: claude-4-best-practices
  url: 
    https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/claude-4-best-practices
  type: official
  weight: 1.0
  title: Claude 4 Best Practices
- id: claude-code-hooks
  url: https://docs.anthropic.com/en/docs/claude-code/hooks
  type: official
  weight: 1.0
  title: Claude Code Hooks Guide
- id: claude-code-issue-13579
  url: https://github.com/anthropics/claude-code/issues/13579
  type: community
  weight: 0.6
  title: 'Claude Code Issue #13579 - Token Waste'
- id: claude-code-memory
  url: https://code.claude.com/docs/en/memory
  type: official
  weight: 1.0
  title: Claude Code Memory Documentation
- id: claude-code-settings
  url: https://code.claude.com/docs/en/settings
  type: official
  weight: 1.0
  title: Claude Code Settings Documentation
- id: claude-context-windows
  url: https://docs.anthropic.com/en/docs/build-with-claude/context-windows
  type: official
  weight: 1.0
  title: Claude Context Windows
- id: claude-md-guide
  url: https://www.builder.io/blog/claude-md-guide
  type: community
  weight: 0.6
  title: Claude.md Guide - Builder.io
- id: claude-md-optimization-study
  url: 
    https://arize.com/blog/claude-md-best-practices-learned-from-optimizing-claude-code-with-prompt-learning/
  type: research
  weight: 0.8
  title: Claude.md Best Practices - Arize
- id: codex-agent-loop
  url: https://openai.com/index/unrolling-the-codex-agent-loop/
  type: official
  weight: 1.0
  title: Unrolling the Codex Agent Loop
- id: dometrain-claude-md-guide
  url: https://dometrain.com/blog/creating-the-perfect-claudemd-for-claude-code/
  type: community
  weight: 0.6
  title: Creating the Perfect CLAUDE.md - Dometrain
- id: enterprise-claude-usage
  url: https://blog.sshh.io/p/how-i-use-every-claude-code-feature
  type: community
  weight: 0.6
  title: How I Use Every Claude Code Feature
- id: instruction-limits-principles
  url: https://www.humanlayer.dev/blog/writing-a-good-claude-md
  type: community
  weight: 0.6
  title: Writing a Good Claude.md - HumanLayer
- id: monorepo-claude-md-organization
  url: 
    https://dev.to/anvodev/how-i-organized-my-claudemd-in-a-monorepo-with-too-many-contexts-37k7
  type: community
  weight: 0.6
  title: Monorepo Claude.md Organization
- id: osmani-ai-coding-workflow
  url: https://addyosmani.com/blog/ai-coding-workflow/
  type: research
  weight: 0.8
  title: AI-Assisted Coding Workflow - Addy Osmani
- id: rules-directory-mechanics
  url: https://claudefa.st/blog/guide/mechanics/rules-directory
  type: community
  weight: 0.6
  title: Rules Directory Mechanics - ClaudeFast
- id: spec-writing-for-agents
  url: https://addyosmani.com/blog/good-spec/
  type: research
  weight: 0.8
  title: Writing Good Specs for AI Agents - Addy Osmani
